version: '3'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: /test/WebApp.IntegrationTests/Dockerfile
    depends_on:
      - webapi
    environment:
      - WEB_API_BASE_URL=http://webapi
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: /src/WebApp/Dockerfile
    ports:
      - 8080:80